### ISSUE TITLE
iOS ListView Refresh with Uneven Rows

### ISSUE THREAD

**Issue by automachina** [warappa/XamlCSS#41] opened 2017-11-22 14:40 UTC
I've been playing with a toy example app to better understand the nuances of your package and came across a strange issue; that may be somehow related to an existing issue in iOS ListView [("NullReferenceException" in "Xamarin.Forms.Platform.iOS.Renderers.LabelRenderer.cs" within "UpdateText()" & "UpdateTextColor()")](https://bugzilla.xamarin.com/show_bug.cgi?id=59813#c36)  Anyways, if I apply a stylesheet and configure the ListView with a HasUnevenRows="true" and refresh the contents of the list (by either pull to refresh or simply clicking a button) it throws a "System.NullReferenceException" at Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateTextColor.  I can avoid this by either setting HasUnevenRows="false" or not applying the stylesheet. In other words, I can have a stylesheet applied and HasUnevenRows="false" or no style sheet applied and HasUnevenRows="true" or "false", anything else will throw the exception when I attempt to refresh the list.  I have a test project [(XamlCssTest)](https://github.com/automachina/XamlCssTest) that seems to demonstrate the issue consistently.  The reason I'm bringing this issue to you and not just chalking it up to the issue mentioned earlier, is because it only seems to happen when I apply a style sheet, so I suspect it may be related, though I could early be mistaken. 

Let me know if there's anything I'm doing wrong or if you have additional questions.

Thanks

Stack Trace:
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateTextColor () [0x00037] in <9a5948fff8254b13a3d593c76c73b9b1>:0 
  at Xamarin.Forms.Platform.iOS.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0005b] in <9a5948fff8254b13a3d593c76c73b9b1>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:138 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\Element.cs:401 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:594 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:391 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:544 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:325 
  at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x00097] in D:\agent\_work\2\s\Xamarin.Forms.Core\Setter.cs:60 
  at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in D:\agent\_work\2\s\Xamarin.Forms.Core\Style.cs:135 
  at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0002b] in D:\agent\_work\2\s\Xamarin.Forms.Core\Style.cs:98 
  at Xamarin.Forms.VisualElement+MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x00156] in D:\agent\_work\2\s\Xamarin.Forms.Core\MergedStyle.cs:163 
  at Xamarin.Forms.VisualElement+MergedStyle.set_Style (Xamarin.Forms.IStyle value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\MergedStyle.cs:39 
  at Xamarin.Forms.VisualElement+<>c.<.cctor>b__213_6 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:80 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0011b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:597 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:391 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:544 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:84 
  at Xamarin.Forms.VisualElement.set_Style (Xamarin.Forms.Style value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:250 
  at XamlCSS.XamarinForms.StyleService.SetStyle (Xamarin.Forms.BindableObject visualElement, Xamarin.Forms.Style style) [0x00008] in <5f1ea2a187614d09b6024c3ec92c5a0a>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x00243] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x0006d] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x0006d] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ExecuteApplyStyles () [0x002ab] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.XamarinForms.Css+<>c__DisplayClass5_0.<StartUiTimer>b__1 () [0x00000] in <5f1ea2a187614d09b6024c3ec92c5a0a>:0 
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/Foundation/NSAction.cs:163 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at XamlCssTest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/gaelanbrewer/Demos/XamlCssTest/iOS/Main.cs:17 
2017-11-22 06:35:21.529 XamlCssTest.iOS[44364:3561735] Unhandled managed exception:
Object reference not set to an instance of an object (System.NullReferenceException)
  at Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateTextColor () [0x00037] in <9a5948fff8254b13a3d593c76c73b9b1>:0 
  at Xamarin.Forms.Platform.iOS.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0005b] in <9a5948fff8254b13a3d593c76c73b9b1>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:138 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\Element.cs:401 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:594 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:391 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:544 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:325 
  at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x00097] in D:\agent\_work\2\s\Xamarin.Forms.Core\Setter.cs:60 
  at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in D:\agent\_work\2\s\Xamarin.Forms.Core\Style.cs:135 
  at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0002b] in D:\agent\_work\2\s\Xamarin.Forms.Core\Style.cs:98 
  at Xamarin.Forms.VisualElement+MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x00156] in D:\agent\_work\2\s\Xamarin.Forms.Core\MergedStyle.cs:163 
  at Xamarin.Forms.VisualElement+MergedStyle.set_Style (Xamarin.Forms.IStyle value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\MergedStyle.cs:39 
  at Xamarin.Forms.VisualElement+<>c.<.cctor>b__213_6 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:80 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0011b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:597 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:391 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:544 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\BindableObject.cs:84 
  at Xamarin.Forms.VisualElement.set_Style (Xamarin.Forms.Style value) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:250 
  at XamlCSS.XamarinForms.StyleService.SetStyle (Xamarin.Forms.BindableObject visualElement, Xamarin.Forms.Style style) [0x00008] in <5f1ea2a187614d09b6024c3ec92c5a0a>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x00243] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x0006d] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ApplyMatchingStyles (TUIElement visualElement, XamlCSS.StyleSheet styleSheet) [0x0006d] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.BaseCss`4[TDependencyObject,TUIElement,TStyle,TDependencyProperty].ExecuteApplyStyles () [0x002ab] in <25a911138f6049919c7386f1606be64b>:0 
  at XamlCSS.XamarinForms.Css+<>c__DisplayClass5_0.<StartUiTimer>b__1 () [0x00000] in <5f1ea2a187614d09b6024c3ec92c5a0a>:0 
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/Foundation/NSAction.cs:163 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at XamlCssTest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/gaelanbrewer/Demos/XamlCssTest/iOS/Main.cs:17 
2017-11-22 06:35:21.529 XamlCssTest.iOS[44364:3561735] critical: Stacktrace:

2017-11-22 06:35:21.529 XamlCssTest.iOS[44364:3561735] critical: 
Native stacktrace:

2017-11-22 06:35:21.541 XamlCssTest.iOS[44364:3561735] critical: 	0   XamlCssTest.iOS                     0x000000010b847794 mono_handle_native_crash + 244
2017-11-22 06:35:21.541 XamlCssTest.iOS[44364:3561735] critical: 	1   libsystem_platform.dylib            0x000000011a6e7f5a _sigtramp + 26
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	2   ???                                 0x000000000000ffff 0x0 + 65535
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	3   libsystem_c.dylib                   0x000000011a2af0e7 abort + 127
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	4   XamlCssTest.iOS                     0x000000010ba0ce9f xamarin_unhandled_exception_handler + 47
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	5   XamlCssTest.iOS                     0x000000010b8b1604 mono_invoke_unhandled_exception_hook + 148
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	6   XamlCssTest.iOS                     0x000000010b847292 mono_handle_exception_internal + 4994
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	7   XamlCssTest.iOS                     0x000000010b845f08 mono_handle_exception + 24
2017-11-22 06:35:21.542 XamlCssTest.iOS[44364:3561735] critical: 	8   XamlCssTest.iOS                     0x000000010b7c85bf mono_amd64_throw_exception + 143
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	9   ???                                 0x0000000135607ae7 0x0 + 5190482663
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	10  XamlCssTest.iOS                     0x000000010b6f5a8c _ZL30native_to_managed_trampoline_9P11objc_objectP13objc_selectorPP11_MonoMethodj + 284
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	11  XamlCssTest.iOS                     0x000000010b6f67c4 -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 52
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	12  Foundation                          0x000000010cc86948 __NSThreadPerformPerform + 334
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	13  CoreFoundation                      0x000000010c061231 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	14  CoreFoundation                      0x000000010c100e41 __CFRunLoopDoSource0 + 81
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	15  CoreFoundation                      0x000000010c045b9b __CFRunLoopDoSources0 + 267
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	16  CoreFoundation                      0x000000010c04512f __CFRunLoopRun + 1279
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	17  CoreFoundation                      0x000000010c0449b9 CFRunLoopRunSpecific + 409
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	18  GraphicsServices                    0x000000011d0399c6 GSEventRunModal + 62
2017-11-22 06:35:21.543 XamlCssTest.iOS[44364:3561735] critical: 	19  UIKit                               0x000000011002f5e8 UIApplicationMain + 159
2017-11-22 06:35:21.544 XamlCssTest.iOS[44364:3561735] critical: 	20  ???                                 0x000000013951baa4 0x0 + 5256624804
2017-11-22 06:35:21.544 XamlCssTest.iOS[44364:3561735] critical: 	21  ???                                 0x000000013951b6ed 0x0 + 5256623853
2017-11-22 06:35:21.544 XamlCssTest.iOS[44364:3561735] critical:

**Comment by warappa** [comment] 2017-11-24 21:26
Hi @automachina ,
thanks for looking into XamlCSS!

I don't own any Apple devices so I cannot reproduce the problem. But I ran the Android project and had no issues. XamlCSS.XamarinForms is exactly the same for Android and iOS (Xamarin.Forms itself is the abstraction), so I'm pretty sure that it has to do with the bug you already found.

Under the hood XamlCSS generates Xamarin.Forms `Style` instances which are packed into the app's `ResourceDictionary`. I guess, if you don't use XamlCSS and write a similar style by hand and assign it to your labels, you should experience the same exception. (If not, a delay may be needed)

**Comment by automachina** [comment] 2017-11-27 23:02
I added styles to the App.xaml Resources and applied them to the list view item template that matched the XamlCss style, disabled the XamlCss style, and now the list refresh does not result in null reference exception.  I've pushed the change to the test project mentioned above.
What exactly did you mean by "a delay may be needed"? 
Where might I put such a delay?

Thanks

**Comment by warappa** [comment] 2017-11-29 22:25
@automachina 
Just created a pull request on your repository (first pull-request ever ;))
https://github.com/automachina/XamlCssTest/pull/1

I tried it again with Android to verify that it behaves the way I intend it to.
Please run it on your iOS device and see if it's triggering the bug.

**Comment by warappa** [comment] 2017-12-04 18:26
@automachina 
Yesterday I fixed a bug which caused your sample's item-page to be not responsive because the stylesheets got applied over and over again - a loop (https://github.com/warappa/XamlCSS/issues/48, and additionally it couldn't handle `Opacity: .5` properly https://github.com/warappa/XamlCSS/issues/47).

This could trigger a bug in Xamarin.Forms because of the repeated updates being forced on Xamarin.Forms' Label renderer.

The new version of XamlCSS is not released yet but will be released shortly.

PS: Could you try to fix the `.5` css "error" in your css and try again if the exception still occurs? If the performance is still bad check the `Errors` property in the stylesheet instance.

**Comment by warappa** [comment] 2017-12-09 10:41
@automachina 
Version 2.1.0 is out which fixes rapid updates.

I still think this problem is related to Xamarin.Forms itself so I'm going to close this issue, but maybe this release works for you until the actual bug in the renderer is fixed.

**Closed as completed by warappa** 2017-12-09 10:41 UTC
